apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-portal-data
  namespace: eurooffice-shared
spec:
  storageClassName: longhorn-2x-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
